### ISSUE TITLE
linewize

### ISSUE THREAD

**Issue by 1Majora1** [STPv22/Dexterity#1]
please update the linewize one

**Comment by STPv22** [comment]
send me the extention info. what do I need to update

**Comment by STPv22** [comment]
@1Majora1

**Comment by STPv22** [comment]
bro

**Comment by STPv22** [comment]
you cant just do this and then dip 😭

**Comment by 1Majora1** [comment]
mg gang i fixed it

**Comment by 1Majora1** [comment]
but here: ifinpabiejbjobcphhaomiifjibpkjlf

**Comment by STPv22** [comment]
thanks 😭 
took you long enugh
